export const FOUNDER_ESIGN_REQUEST = "FOUNDER_ESIGN_REQUEST";
export const FOUNDER_ESIGN_SUCCESS = "FOUNDER_ESIGN_SUCCESS";
export const FOUNDER_ESIGN_FAILED = "FOUNDER_ESIGN_FAILED";

export const FOUNDER_CAMPAIGN_REQUEST = "FOUNDER_CAMPAIGN_REQUEST";
export const FOUNDER_CAMPAIGN_SUCCESS = "FOUNDER_CAMPAIGN_SUCCESS";
export const FOUNDER_CAMPAIGN_FAILED = "FOUNDER_CAMPAIGN_FAILED";