export const FOUNDER_SIGNUP_DATASTORE_REQUEST = "FOUNDER_SIGNUP_DATASTORE_REQUEST";
export const FOUNDER_SIGNUP_DATASTORE_SUCCESS = "FOUNDER_SIGNUP_DATASTORE_SUCCESS";
export const FOUNDER_SIGNUP_DATASTORE_FAILED = "FOUNDER_SIGNUP_DATASTORE_FAILED";