export const VERIFY_PAN_REQUEST = "VERIFY_PAN_REQUEST";
export const VERIFY_PAN_SUCCESS = "VERIFY_PAN_SUCCESS";
export const VERIFY_PAN_FAILED = "VERIFY_PAN_FAILED";

export const VERIFY_BANK_REQUEST = "VERIFY_BANK_REQUEST";
export const VERIFY_BANK_SUCCESS = "VERIFY_BANK_SUCCESS";
export const VERIFY_BANK_FAILED = "VERIFY_BANK_FAILED";
